// print is used for reporting test results so it is allowed in this file
// ignore_for_file: avoid_print

import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_test/flutter_test.dart';
import 'package:gait_sense/models/feature_window.dart';
import 'package:gait_sense/models/sensor_sample.dart';
import 'package:gait_sense/services/feature_pipeline.dart';
import 'package:gait_sense/services/har_inference.dart';
import 'package:integration_test/integration_test.dart';

/// On-device inference parity for the Dart HAR pipeline against the Python
/// TFLite reference. Runs on a real Android device so it exercises the exact
/// `libtensorflowlite_c` binary the app ships with (the desktop test runner has
/// no TFLite native library). Fixtures are generated by
/// `ml/scripts/export_parity_fixtures.py` and bundled as assets.
///
/// Acceptance:
///  - predicted argmax label agreement >= 99% across all windows
///  - per-class probability max abs error < 0.01
///  - inference latency p50 < 50 ms per window
///
/// Bonus check: the Dart feature pipeline is re-validated on ARM against the
/// Python normalized windows (< 1e-4), confirming the offline feature-pipeline
/// parity holds on the target architecture, not only on the x64 host.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  const fixtureNames = ['wlk_7_sub_5.infer.json', 'sit_5_sub_5.infer.json'];
  const probTolerance = 0.01;
  const windowTolerance = 1e-4;
  const minLabelAgreement = 0.99;
  const latencyBudgetMs = 50;

  late HarInference inference;

  setUpAll(() async {
    inference = await HarInference.load();
  });
  tearDownAll(() async {
    await inference.close();
  });

  Future<Map<String, dynamic>> loadFixture(String name) async {
    final raw = await rootBundle.loadString('test/fixtures/parity/$name');
    return jsonDecode(raw) as Map<String, dynamic>;
  }

  List<SensorSample> samplesFrom(Map<String, dynamic> fixture) {
    final input = (fixture['input'] as List).cast<List<dynamic>>();
    return [
      for (final row in input)
        SensorSample(
          timestamp: DateTime.fromMillisecondsSinceEpoch(0),
          gravityX: (row[0] as num).toDouble(),
          gravityY: (row[1] as num).toDouble(),
          gravityZ: (row[2] as num).toDouble(),
          userAccelerationX: (row[3] as num).toDouble(),
          userAccelerationY: (row[4] as num).toDouble(),
          userAccelerationZ: (row[5] as num).toDouble(),
          rotationRateX: (row[6] as num).toDouble(),
          rotationRateY: (row[7] as num).toDouble(),
          rotationRateZ: (row[8] as num).toDouble(),
        ),
    ];
  }

  testWidgets('Dart pipeline + TFLite matches Python reference', (
    tester,
  ) async {
    var totalWindows = 0;
    var labelMatches = 0;
    var maxProbError = 0.0;
    var maxWindowError = 0.0;
    final report = StringBuffer('\n');

    for (final name in fixtureNames) {
      final fixture = await loadFixture(name);
      final samples = samplesFrom(fixture);
      final expectedWindows = (fixture['windows'] as List)
          .map(
            (w) => (w as List)
                .map(
                  (r) => (r as List).map((v) => (v as num).toDouble()).toList(),
                )
                .toList(),
          )
          .toList();
      final expectedProbs = (fixture['probabilities'] as List)
          .map((p) => (p as List).map((v) => (v as num).toDouble()).toList())
          .toList();
      final expectedLabels = (fixture['pred_label_names'] as List)
          .cast<String>();

      final features = FeaturePipeline.computeBlockFeatures(samples);
      final dartWindows = FeaturePipeline.windows(features);

      expect(
        dartWindows.length,
        expectedWindows.length,
        reason: 'window count mismatch for $name',
      );

      var fixtureLabelMatches = 0;
      var fixtureMaxProbError = 0.0;
      var fixtureMaxWindowError = 0.0;

      for (var w = 0; w < dartWindows.length; w++) {
        // Bonus: Dart pipeline vs Python normalized windows, on ARM.
        for (var t = 0; t < FeatureWindow.windowSize; t++) {
          for (var c = 0; c < FeatureWindow.channelCount; c++) {
            final e = (dartWindows[w][t][c] - expectedWindows[w][t][c]).abs();
            if (e > fixtureMaxWindowError) fixtureMaxWindowError = e;
          }
        }

        final prediction = await inference.predict(
          FeatureWindow(
            data: dartWindows[w],
            endTimestamp: DateTime.fromMillisecondsSinceEpoch(0),
            endSampleIndex: w,
          ),
        );

        if (prediction.label == expectedLabels[w]) fixtureLabelMatches++;
        for (var c = 0; c < prediction.probabilities.length; c++) {
          final e = (prediction.probabilities[c] - expectedProbs[w][c]).abs();
          if (e > fixtureMaxProbError) fixtureMaxProbError = e;
        }
      }

      totalWindows += dartWindows.length;
      labelMatches += fixtureLabelMatches;
      maxProbError = maxProbError > fixtureMaxProbError
          ? maxProbError
          : fixtureMaxProbError;
      maxWindowError = maxWindowError > fixtureMaxWindowError
          ? maxWindowError
          : fixtureMaxWindowError;

      report.writeln(
        '$name: ${dartWindows.length} windows | '
        'labels $fixtureLabelMatches/${dartWindows.length} | '
        'max prob err ${fixtureMaxProbError.toStringAsExponential(3)} | '
        'max window err ${fixtureMaxWindowError.toStringAsExponential(3)}',
      );

      // Per-fixture hard gates.
      expect(
        fixtureMaxWindowError,
        lessThan(windowTolerance),
        reason: '$name feature-pipeline parity exceeds $windowTolerance on ARM',
      );
      expect(
        fixtureMaxProbError,
        lessThan(probTolerance),
        reason: '$name probability error exceeds $probTolerance',
      );
    }

    final agreement = labelMatches / totalWindows;
    report.writeln(
      'POOLED: $labelMatches/$totalWindows labels agree '
      '(${(agreement * 100).toStringAsFixed(1)}%) | '
      'max prob err ${maxProbError.toStringAsExponential(3)}',
    );
    // Diagnostic table surfaced in the test runner output for the spec report.
    print(report);

    expect(
      agreement,
      greaterThanOrEqualTo(minLabelAgreement),
      reason: 'label agreement below ${minLabelAgreement * 100}%',
    );
  });

  testWidgets('inference latency p50 < $latencyBudgetMs ms', (tester) async {
    final fixture = await loadFixture(fixtureNames.first);
    final samples = samplesFrom(fixture);
    final features = FeaturePipeline.computeBlockFeatures(samples);
    final window = FeatureWindow(
      data: FeaturePipeline.windows(features).first,
      endTimestamp: DateTime.fromMillisecondsSinceEpoch(0),
      endSampleIndex: 0,
    );

    // Warm-up: first call includes isolate spin-up / lazy delegate init.
    for (var i = 0; i < 5; i++) {
      await inference.predict(window);
    }

    final latencies = <int>[];
    for (var i = 0; i < 50; i++) {
      latencies.add((await inference.predict(window)).inferenceLatencyMs);
    }
    latencies.sort();
    final p50 = latencies[(latencies.length * 0.50).floor()];
    final p95 = latencies[(latencies.length * 0.95).floor()];
    // Latency stats surfaced in the test runner output for the spec report.
    print('\ninference latency: p50=${p50}ms p95=${p95}ms (n=50)\n');

    expect(
      p50,
      lessThan(latencyBudgetMs),
      reason: 'p50 latency $p50 ms exceeds $latencyBudgetMs ms budget',
    );
  });
}
