import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter_test/flutter_test.dart';
import 'package:gait_sense/models/feature_window.dart';
import 'package:gait_sense/models/sensor_sample.dart';
import 'package:gait_sense/services/feature_pipeline.dart';

/// Numerical-parity tests for the **causal live path**
/// ([StreamingFeatureExtractor]) against the Python reference
/// `utils.streaming_offline_compare.streaming_windows`.
///
/// This is the path the app actually runs during a recording session, and it
/// is not the one covered by `feature_pipeline_test.dart` (that test feeds a
/// whole session as one block, matching the non-causal smoothing the model was
/// trained on). The Python side of this comparison is the *same* function that
/// produces the streaming-vs-offline comparison numbers reported in the
/// thesis, so the figures quoted there describe code verified to match the app.
///
/// Fixtures are generated by `ml/scripts/export_parity_fixtures.py`
/// (`*.streaming.json`). Truncating the input is exactly lossless for this
/// path: the extractor never looks further back than `contextSamples`, so
/// window k over a prefix is bit-identical to window k over the full session.
///
/// Acceptance: identical window count, identical `endSampleIndex` sequence, and
/// max absolute error < 1e-4 across all windows and all 8 channels.
void main() {
  const tolerance = 1e-4;

  Map<String, dynamic> loadFixture(String name) =>
      jsonDecode(
            File('test/fixtures/parity/$name').readAsStringSync(),
          )
          as Map<String, dynamic>;

  /// Builds samples from the 9 raw channels in `input_channel_order`:
  /// gravity.{x,y,z}, userAcceleration.{x,y,z}, rotationRate.{x,y,z}.
  List<SensorSample> samplesFrom(Map<String, dynamic> fixture) {
    final input = (fixture['input'] as List).cast<List<dynamic>>();
    return [
      for (var t = 0; t < input.length; t++)
        SensorSample(
          // 20 ms apart so timestamps reflect the 50 Hz the fixture assumes.
          timestamp: DateTime.fromMillisecondsSinceEpoch(t * 20),
          gravityX: (input[t][0] as num).toDouble(),
          gravityY: (input[t][1] as num).toDouble(),
          gravityZ: (input[t][2] as num).toDouble(),
          userAccelerationX: (input[t][3] as num).toDouble(),
          userAccelerationY: (input[t][4] as num).toDouble(),
          userAccelerationZ: (input[t][5] as num).toDouble(),
          rotationRateX: (input[t][6] as num).toDouble(),
          rotationRateY: (input[t][7] as num).toDouble(),
          rotationRateZ: (input[t][8] as num).toDouble(),
        ),
    ];
  }

  List<List<List<double>>> expectedWindows(Map<String, dynamic> fixture) =>
      (fixture['windows'] as List)
          .map(
            (w) => (w as List)
                .map(
                  (r) => (r as List).map((v) => (v as num).toDouble()).toList(),
                )
                .toList(),
          )
          .toList();

  void reportAndAssert(String fixtureName) {
    final fixture = loadFixture(fixtureName);
    final meta = fixture['meta'] as Map<String, dynamic>;
    final samples = samplesFrom(fixture);
    final expected = expectedWindows(fixture);
    final expectedEnds = (fixture['end_sample_indices'] as List)
        .map((v) => (v as num).toInt())
        .toList();

    // The fixture was generated for a specific context length; if the extractor
    // default changes, the comparison is no longer apples-to-apples.
    expect(
      meta['context_samples'],
      StreamingFeatureExtractor().contextSamples,
      reason:
          'fixture $fixtureName was generated with contextSamples='
          '${meta['context_samples']}, but StreamingFeatureExtractor now '
          'defaults to ${StreamingFeatureExtractor().contextSamples}; '
          'regenerate the fixtures with ml/scripts/export_parity_fixtures.py',
    );

    // Feed the extractor sample by sample, exactly as FeaturePipelineBloc does.
    final extractor = StreamingFeatureExtractor();
    final actual = <FeatureWindow>[];
    for (final sample in samples) {
      final window = extractor.add(sample);
      if (window != null) actual.add(window);
    }

    expect(
      actual.length,
      expected.length,
      reason: 'window count mismatch for $fixtureName',
    );
    expect(
      actual.map((w) => w.endSampleIndex).toList(),
      expectedEnds,
      reason: 'emission points differ for $fixtureName',
    );

    final maxErr = List<double>.filled(FeatureWindow.channelCount, 0);
    for (var w = 0; w < expected.length; w++) {
      for (var t = 0; t < FeatureWindow.windowSize; t++) {
        for (var c = 0; c < FeatureWindow.channelCount; c++) {
          final err = (actual[w].data[t][c] - expected[w][t][c]).abs();
          if (err > maxErr[c]) maxErr[c] = err;
        }
      }
    }

    final buffer = StringBuffer(
      '\nmax abs error per channel (causal path) — $fixtureName\n',
    );
    for (var c = 0; c < FeatureWindow.channelCount; c++) {
      buffer.writeln(
        '  ${FeatureWindow.channelOrder[c].padRight(8)} '
        '${maxErr[c].toStringAsExponential(3)}',
      );
    }
    // Diagnostic table (channel-wise max abs errors)
    // ignore: avoid_print
    print(buffer);

    for (var c = 0; c < FeatureWindow.channelCount; c++) {
      expect(
        maxErr[c],
        lessThan(tolerance),
        reason: 'channel ${FeatureWindow.channelOrder[c]} exceeds $tolerance',
      );
    }
  }

  test('walking session: causal path matches Python reference (< 1e-4)', () {
    reportAndAssert('wlk_7_sub_5.streaming.json');
  });

  test('static session: causal path matches Python reference (< 1e-4)', () {
    reportAndAssert('sit_5_sub_5.streaming.json');
  });

  test('context buffer is longer than the smoothing kernel', () {
    // Regression guard. _movingAverageSame returns its input unchanged whenever
    // the block is not longer than the kernel, so a contextSamples value at or
    // below the kernel length silently disables the walking-direction smoothing
    // and collapses a_f_mag into a duplicate of a_h and a_s_mag into a constant
    // zero — without any error at run time.
    final kernelSamples = (FeaturePipeline.smoothSeconds * FeaturePipeline.fsHz)
        .round();
    expect(
      StreamingFeatureExtractor().contextSamples,
      greaterThan(kernelSamples),
      reason:
          'contextSamples must exceed the $kernelSamples-sample smoothing '
          'kernel or the moving average never fires',
    );
  });

  test('startup ramp is exactly two windows and is reported as such', () {
    // While the buffer is not longer than the kernel the smoothing is a no-op,
    // so a_f_mag degenerates to a_h and a_s_mag to a constant. This test pins
    // down how many windows are affected, so the limitation documented in the
    // thesis stays in sync with the code.
    final kernelSamples = (FeaturePipeline.smoothSeconds * FeaturePipeline.fsHz)
        .round();
    const step = FeatureWindow.windowSize ~/ 2;
    var affected = 0;
    for (
      var bufferLength = FeatureWindow.windowSize;
      bufferLength <= kernelSamples;
      bufferLength += step
    ) {
      affected++;
    }
    expect(affected, 2);

    // And confirm the degeneracy really is what is claimed, on real data.
    final fixture = loadFixture('wlk_7_sub_5.streaming.json');
    final samples = samplesFrom(fixture);
    final extractor = StreamingFeatureExtractor();
    final emitted = <FeatureWindow>[];
    for (final sample in samples) {
      final window = extractor.add(sample);
      if (window != null) emitted.add(window);
    }
    const aH = 3;
    const aFMag = 5;
    const aSMag = 6;
    for (var w = 0; w < affected; w++) {
      var maxDiff = 0.0;
      var maxAbsS = 0.0;
      for (var t = 0; t < FeatureWindow.windowSize; t++) {
        maxDiff = max(
          maxDiff,
          (emitted[w].data[t][aFMag] - emitted[w].data[t][aH]).abs(),
        );
        maxAbsS = max(maxAbsS, emitted[w].data[t][aSMag].abs());
      }
      expect(maxDiff, lessThan(1e-9), reason: 'window $w: a_f_mag != a_h');
      expect(maxAbsS, lessThan(1e-6), reason: 'window $w: a_s_mag != 0');
    }
    // The third window must no longer be degenerate.
    final firstSmoothed = emitted[affected].data;
    var maxDiffAfter = 0.0;
    for (var t = 0; t < FeatureWindow.windowSize; t++) {
      maxDiffAfter = max(
        maxDiffAfter,
        (firstSmoothed[t][aFMag] - firstSmoothed[t][aH]).abs(),
      );
    }
    expect(maxDiffAfter, greaterThan(1e-3));
  });
}
