import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:gait_sense/models/feature_window.dart';
import 'package:gait_sense/models/sensor_sample.dart';
import 'package:gait_sense/services/feature_pipeline.dart';

/// Numerical-parity tests for the Dart walking-frame v2 pipeline against the
/// Python reference (`compute_walking_frame_features_v2`). Fixtures are
/// generated by `ml/scripts/export_parity_fixtures.py`.
///
/// Acceptance: max absolute error < 1e-4 across all windows and
/// all 8 channels. The tolerance also absorbs the Python `normalize_dyn`
/// float32 cast versus Dart's float64 arithmetic.
void main() {
  const tolerance = 1e-4;

  /// Loads a fixture, runs the Dart pipeline, and returns the per-channel max
  /// absolute error against the expected normalized windows.
  List<double> channelMaxErrors(String fixtureName) {
    final file = File('test/fixtures/parity/$fixtureName');
    final fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;

    // Build samples from the 9 raw channels in input_channel_order:
    // gravity.{x,y,z}, userAcceleration.{x,y,z}, rotationRate.{x,y,z}.
    final input = (fixture['input'] as List).cast<List<dynamic>>();
    final samples = [
      for (final row in input)
        SensorSample(
          timestamp: DateTime.fromMillisecondsSinceEpoch(0),
          gravityX: (row[0] as num).toDouble(),
          gravityY: (row[1] as num).toDouble(),
          gravityZ: (row[2] as num).toDouble(),
          userAccelerationX: (row[3] as num).toDouble(),
          userAccelerationY: (row[4] as num).toDouble(),
          userAccelerationZ: (row[5] as num).toDouble(),
          rotationRateX: (row[6] as num).toDouble(),
          rotationRateY: (row[7] as num).toDouble(),
          rotationRateZ: (row[8] as num).toDouble(),
        ),
    ];

    final expected = (fixture['windows'] as List)
        .map(
          (w) => (w as List)
              .map(
                (r) => (r as List).map((v) => (v as num).toDouble()).toList(),
              )
              .toList(),
        )
        .toList();

    final features = FeaturePipeline.computeBlockFeatures(samples);
    final actual = FeaturePipeline.windows(features);

    expect(
      actual.length,
      expected.length,
      reason: 'window count mismatch for $fixtureName',
    );

    final maxErr = List<double>.filled(FeatureWindow.channelCount, 0);
    for (var w = 0; w < expected.length; w++) {
      for (var t = 0; t < FeatureWindow.windowSize; t++) {
        for (var c = 0; c < FeatureWindow.channelCount; c++) {
          final err = (actual[w][t][c] - expected[w][t][c]).abs();
          if (err > maxErr[c]) maxErr[c] = err;
        }
      }
    }
    return maxErr;
  }

  void reportAndAssert(String fixtureName) {
    final maxErr = channelMaxErrors(fixtureName);
    final buffer = StringBuffer('\nmax abs error per channel — $fixtureName\n');
    for (var c = 0; c < FeatureWindow.channelCount; c++) {
      buffer.writeln(
        '  ${FeatureWindow.channelOrder[c].padRight(8)} '
        '${maxErr[c].toStringAsExponential(3)}',
      );
    }
    // Diagnostic table (channel-wise max abs errors)
    // ignore: avoid_print
    print(buffer);
    for (var c = 0; c < FeatureWindow.channelCount; c++) {
      expect(
        maxErr[c],
        lessThan(tolerance),
        reason: 'channel ${FeatureWindow.channelOrder[c]} exceeds $tolerance',
      );
    }
  }

  test('walking session matches Python reference (< 1e-4)', () {
    reportAndAssert('wlk_7_sub_5.json');
  });

  test('static session exercises fallback branch and matches (< 1e-4)', () {
    reportAndAssert('sit_5_sub_5.json');
  });
}
